### ISSUE TITLE
Map component

### ISSUE THREAD

**Issue by MLoth** [MLoth/Birds-#11]
### Setup
- [x] set developer API in .env
- [x] install packages in pwa

### Props

- [x] Set coordinates of map
- [x] Set marker on map
- [x] Set polygon on map

### Emit
- [x] Return coordinates of tap / click on map

### API
- [ ] Replace location with coordinates (some work)

**Comment by MLoth** [comment]
Need help?

**Comment by MLoth** [comment]
Ik zal ook nog even develop up-to-date brengen.

**Comment by DupontAchille** [comment]
Bedankt!
