### ISSUE TITLE
npm run build not working

### ISSUE THREAD

**Issue by QuintenMuyllaert** [MLoth/Birds-#3]
npm run build not working.

Steps to reproduce : 
- clone repo
- cd into pwa
- npm install
- npm run build

**Expected result :** 
- The project builds and outputs to dist folder

**Actual result :** 
![image](https://user-images.githubusercontent.com/72012305/191439095-e48e9aeb-eaf8-4e10-bab4-df7a71005a1d.png)

**Potential fix :** 
- Switch vue-tsc to normal tsc.

[💚 Update and fix npm run build](https://github.com/QuintenMuyllaert/Birds-QuintenMuyllaert/commit/45ec0011ddf707f1c5f69f4eb9827e807d473cf8)

**Additional comment :**
Curious as to why neither the root project and my fork are building using vue-tsc as it is the default installed by vite.

**Comment by MLoth** [comment]
This can happen when there is no export in the script section. 
A good fix is to export an empty object:
```vue
<script lang="ts">
  export default {} // Ah, this is a JS-thingy... 😯
</script>
```
