### ISSUE TITLE
Backend start with GrapqhQL

### ISSUE THREAD

**Issue by MLoth** [MLoth/Birds-#6]
# Birds Nest.JS & GraphQL
Werk verder in de Bird repo
## Voorbereiding
- [x] Plaats een `docker-compose.yml` in de root zodat je een mongodb birds kan aanmaken
- [x] Gebruik de NestJS cli om een nieuw nest project aan te maken met als naam backend 
  - [x] `nest new backend` 
- [x] Verwijder de node_modules uit de aangemaakte folder
- [x] Voeg in de `package.json` een nieuwe workspace backend toe
- [x] Voer `npm i` uit in de root folder 
- [x] Pas de `main.ts` aan zodat je een port kan kiezen én dat je in de console een boodschap krijgt

## Documentatie
https://docs.nestjs.com/techniques/database
https://docs.nestjs.com/graphql/quick-start
https://docs.nestjs.com/cli/usages 

## TypeORM
Importeer in **app.module** de TypeORM module met de correcte settings om verbinding te maken met de mongodb
- [x] Installeer de correcte packages

## GraphQL
- https://docs.nestjs.com/graphql/quick-start

Importeer in `**app.module**` de GraphQL module, zodat de playground van Apollo actief komt
- [x] Installeer de correcte packages

Je zal een error krijgen omdat er nog geen entity is die een GraphQL schema genereert

### Maak een birds entity met bijhorend schema
- [ ] Gebruik de cli om een CRUD graphql resource aan te maken voor birds. Gebruik het meervoud
  - `nest g resource birds`
  - Kies voor GraphQL: Code First!
  - Merk op dat er nu geen controller maar resolver wordt aangemaakt.
  
### app.module
*The autoSchemaFile property value is the path where your automatically generated schema will be created. Alternatively, the schema can be generated on-the-fly in memory. To enable this, set the autoSchemaFile property to true:*

- Zet de autoSchemaFile property op true, zodat alle entities met een `@ObjectType()` decorator automatisch herkend worden en er voor deze een schema wordt aangemaakt

### Bird entity
- Elk field heeft een decorator voor GraphQL en eentje voor TypeORM
**bird.entity.ts**
```ts
import { Field, ID, ObjectType } from '@nestjs/graphql';
import { ObjectId } from 'mongodb';
import {
  Column,
  CreateDateColumn,
  Entity,
  ObjectIdColumn,
  UpdateDateColumn,
} from 'typeorm';

@Entity()
@ObjectType({ description: 'bird' })
export class Bird {
  @Field(() => ID) // GraphQL
  @ObjectIdColumn({ name: '_id' })//typeORM // Map this field to the (generated) _id column in the database
  id: ObjectId;

  @Field()// GraphQL
  @Column()//typeORM
  name: string;

  @Field()
  @Column()
  fullname: string;

  @Field()
  @Column()
  category: string;

  @Field()
  @Column()
  url: string;

  @Field({ defaultValue: 0 })
  @Column()
  observations: number;

  @Field({ nullable: true })
  @Column()
  description?: string;

  @Field({ nullable: true })
  @CreateDateColumn({ type: 'timestamp', nullable: true })
  createdAt?: Date;

  @Field({ nullable: true })
  @UpdateDateColumn({ type: 'timestamp', nullable: true })
  updatedAt?: Date;
}
```
### dto/create-bird.input.ts
- Let op de decorator @inputType(). Deze class heeft enkel en alleen een GraphQL decorators. Omdat het niet gebruikt wordt om documents aan te maken in mongodb.

```ts 
import { InputType, Int, Field } from '@nestjs/graphql';

@InputType()
export class CreateBirdInput {
  @Field() // GraphQL
  name: string;

  @Field() // GraphQL
  fullname: string;

  @Field() // GraphQL
  category: string;

  @Field() // GraphQL
  url: string;

  @Field({ defaultValue: 0 }) // GraphQL
  observations: number;

  @Field({ nullable: true }) // GraphQL
  description?: string;
}
```
### dto/update-bird.input.ts
- Deze class erft over van de CreateBirdInput en voegt nog een extra field id toe als string
```ts
import { CreateBirdInput } from './create-bird.input';
import { InputType, Field, PartialType } from '@nestjs/graphql';

@InputType()
export class UpdateBirdInput extends PartialType(CreateBirdInput) {
  @Field() // GraphQL
  id: string;
}
```
### birds.resolver.ts
- De resolver heeft enkele decorators voor graphql. 
- Je herkent de Query en Mutation uit graphql
- De bussines logica zal terug geïnjecteerd worden vanuit een Service.
- [x] Je ziet dat er een fout bij de update Mutation is. Dit komt omdat onze id's, die binnenkomen als parameter, geen *number* maar *String* zijn. 
- [x] Pas zowel de **update** als **remove** Mutation aan.
- [x] Pas ook de *findOne* Query aan.
### birds.services.ts
- [x] Controleer de id's bij *service* en pas aan indien nodig

## Playground
De playground is vanaf nu bereikbaar, maar omdat er nog geen code geschreven is om data op te halen uit de databank zal deze nog errors geven als je een query probeert uit te voeren;
http://localhost:3004/graphql

- [x] Controleer de verschillende schema's en doc via de 2 knoppen rechts

## birds.service
- [x] Injecteer de TypeORM repository voor Birds in de constructor
```ts
@Injectable()
export class BirdService {
  constructor(
    @InjectRepository(Bird)
    private birdsRepository: Repository<Bird>,
  ) {}
```
- [x] create
    - Kies als return type een promise van type bird
   ```ts
    create(createBirdInput: CreateBirdInput): Promise<Bird> {
    console.log('This action adds a new bird');
    return this.birdsRepository.save(createBirdInput);
  }```
- [x] findAll
    - Het return type is een promise van een array van Birds
```ts
  findAll(): Promise<Bird[]> {
    console.log(`This action returns all bird`);
    return this.birdsRepository.find();
  }
```
- [x] find
    - Vergeet hier het id niet om te zetten naar een ObjectId van mongodb
```ts
  findOne(id: String): Promise<Bird> {
    console.log(`This action returns a #${id} bird`);
    const parsedId = new Object(id);
    // @ts-ignore
    return this.birdsRepository.findOneBy({ _id: parsedId });
  }
```

- [x] update  async update(id: String, updateBirdInput:
```ts
  async update(id: String, updateBirdInput: UpdateBirdInput): Promise<Bird> {
    console.log(`This action updates a #${id} bird`);
    const parsedId = new ObjectId(id);

    const b = await this.birdsRepository.findOne(parsedId);
    b.name = updateBirdInput.name;
    b.fullname = updateBirdInput.fullname;
    b.category = updateBirdInput.category;
    b.url = updateBirdInput.url;
    b.observations = updateBirdInput.observations;
    b.description = updateBirdInput.description;

    await this.birdsRepository.save(b); //<--- save for updateat field
    return this.birdsRepository.findOne(parsedId);
  }
```
- [x] remove
```ts
  async remove(id: String): Promise<boolean> {
    console.log(`This action removes a #${id} bird`);

    const parsedId = new ObjectId(id); //convert string to ObjectId

    const r = await this.birdsRepository.delete(parsedId);
    if (r.affected) {
      return Promise.resolve(true);
    } else {
      return Promise.resolve(false);
    }
  }
  ```

## Nog steeds een error 💣
  ```
  Error: Nest can't resolve dependencies of the BirdService (?). Please make sure that the argument BirdRepository at index [0] is available in the BirdModule context.

Potential solutions:
- If BirdRepository is a provider, is it part of the current BirdModule?
- If BirdRepository is exported from a separate @Module, is that module imported within BirdModule?
  @Module({
    imports: [ /* the Module containing BirdRepository */ ]
  })
  ```
  ### birds.module
  - [x] Importeer in birds.module de TypeOrmModule.forFeature([Bird]), zodat deze kan geïnjecteerd worden in de service

# Playground
- [x] Test de Mutations en Queries uit

```
mutation {
  createBird(
    createBirdInput: {
      name: "mees"
      fullname: "blauwe mees"
      category: "vliegende vogel"
      url: "img.jpg"
    }
  ) {
    id
    name
    fullname
  }
}
```

```
query {
  bird(id: "632f1ae2882f080cb1071a09") {
    id
    name
  }
}

```

```
query {
  birds {
    id
    name
  }
}

```

```
mutation {
  updateBird(
    updateBirdInput: {
      id:"632f1ae2882f080cb1071a09"
      name: "mees"
      fullname: "blue mees"
      category: "vliegende vogel"
      url: "img.jpg"
    }
  ) {
    id
    name
    fullname
  }
}
```
```
mutation {
  removeBird(
    id:"632f1ae2882f080cb1071a09"
  ) 
}
```

## Maak een entity **area**  met bijhorende resolver
*Gebruik niet location als classname -> kan errors geven omdat het een gereserveerd woord is van mongo*
 - `nest g resource areas`

Een *area* heeft volgende fields
- een id
- een name
- het create en update moment

## Maak een entity **observation** met bijhorende resolver
 - `nest g resource observations`

Een *observation* heeft volgende fields
- een id
- een name
- een userid (string)
- een weather(condition) (string)
- het create en update moment

Test alles uit in de playground

### Bijhouden van de ge-observeerde bird
- In het document observation wil je enkel het ObjectId van de gespotte bird bijhouden. = TypeORM
  - Voeg toe aan observation.entity: 
    - een field birdId, en geef deze enkel een @Column() decorator
    ```ts
    @Column() //typeorm mongo
    birdId: string;
    ```
  - Voeg toe aan dto/create-observation.entity: 
    ```ts
    @Field() //graphql
    birdId: string;
    ```

Test uit in de playground of je een observation kan toevoegen met een birdId. Je zal via mongo-express moeten kijken. Want je "exposed" de bird niet in de observation type.

Je wil echter de mogelijkheid geven aan de gebruiker om de volledige bird op te vragen van een observation, dus niet enkel zijn id.
- Voeg toe aan observation.entity:
  ```ts
  @Field(() => Bird) //=> GraphQL
  bird: Bird; // GraphQL will need a resolver for this
  ```
- Test in de playground
```
query {
  observations {
    id
    name
    createdAt
    bird {
      id
      name
      fullname
    }
  }
}
```
💣 Je krijgt volgende error, want GraphQL weet niet hoe hij deze Bird moet vinden (resolven)
```json
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Observation.bird.",
```
### observations.resolver
Plaats in de observation.resolver een extra functiondecorator `@ResolveField()` 
- Deze functie krijgt als parameter zijn parent object mee.
- Uit dit parentObject kan je het birdId opvragen, want dit is een eenvoudig field
- Vervolgens is het aan de developer hoe hij dit field "oplost". In dit voorbeeld spreek je gewoon de birdService aan. Maar het kan ook zijn dat je een externe API call moet doen om bv de huidige weersituatie van een bepaalde locatie op te vragen
  - De birdsService, zal nu ook geinjecteerd moeten worden in de constructor.
  - Doordat je de Bird ORM en BirdsService gebruikt, zullen ook deze toegevoegd worden in de observations.module
***observations.resolver.ts**
```ts
import {
  Resolver,
  ResolveField,
  Parent,
} from '@nestjs/graphql';
import { BirdService } from 'src/bird/bird.service';

@Resolver(() => Observation)
export class ObservationsResolver {
  constructor(
    private readonly observationsService: ObservationsService,
    private readonly birdsService: BirdsService,
  ) {}


  @ResolveField()
  async bird(@Parent() parentObject: Observation) {
    console.log('Get category for observation', parentObject);
    const { birdId } = parentObject; //use destructuring to get the categoryID from the parentObject
    return this.birdsService.findOne(birdId);
  }
}
```
***observations.module.ts**
```ts
@Module({
  imports: [TypeOrmModule.forFeature([Observation, Bird])],
  providers: [ObservationsResolver, ObservationsService, BirdService],
})
export class ObservationsModule {}
```
- [x] Test uit in de playground
- [x] Zorg dat aan een observation ook een area gekoppeld wordt.

# Seed de database
## packages

- https://www.npmjs.com/package/nestjs-command
- https://www.npmjs.com/search?q=class-transformer

## Installation
```
npm i nestjs-command yargs -w backend
npm i class-transformer -w backend
npm i -D @types/yargs -w backend
```

## Implementation
We gaan ervan uit dat er reeds een entity en service class is gemaakt voor de gewenste entity.
Als voorbeeld nemen we birds

maak volgende bestanden aan
- seed/
  - data/
    - birds.json
  - seed.service.ts
  - seed.command.ts
  - seed.module.ts

### seed.service.ts
- Je laadt de json file in. Vergeet tsconfig niet aan te passen
- Je injecteert de gewenste typeorm repositories in de constructor
- Via de functie plainToInstance parse je de json naar Objecten
- via de standaard typeorm voeg je de objecten toe
```typescript
import { Injectable } from '@nestjs/common'
import { InjectRepository } from '@nestjs/typeorm'
import { Bird } from '../birds/entities/bird.entity'
import { Repository } from 'typeorm'
import * as jsonBirdsSeed from './data/birds.json' //tsconfig "resolveJsonModule": true,
import { plainToInstance } from 'class-transformer' //https://www.npmjs.com/package/class-transformer

@Injectable()
export class DatabaseSeedService {
  constructor(
    @InjectRepository(Bird)
    private birdsRepository: Repository<Bird>,
  ) {}

  async addAllBirds(): Promise<Bird[]> {
    let theBirds: Bird[] = [];
    //@ts-ignore
    for (let jsonb of jsonBirdsSeed.birds) {
      //let b = plainToInstance(Bird, jsonb);
      const b = new Bird();
      b.name = jsonb.name;
      b.fullname = jsonb.fullName;
      b.category = '';
      b.observations = 0;
      b.url = jsonb.url;
      b.description = jsonb.description;

      theBirds.push(b);
    }

    return this.birdsRepository.save(theBirds);
  }

  async deleteAllBirds(): Promise<void> {
    await this.birdsRepository.delete({})
    return Promise.resolve()
  }
}
```

### seed.command.ts
- Deze class is vergelijkbaar met de resolvers voor graphql.
  - Maakt de commands bereikbaar voor het command prompt
  - Via decorators boven elke functie
- In de constructor injecteer je de service class 

```typescript
import { Command } from 'nestjs-command'
import { Injectable } from '@nestjs/common'
import { DatabaseSeedService } from './seed.service'

@Injectable()
export class DatabaseSeedCommand {
  constructor(private readonly seedService: DatabaseSeedService) {}

  @Command({
    command: 'seed:database',
    describe: 'seed the database',
  })
  async seed() {
    console.log('🌱 Start seeding')
    const r = await this.seedService.addAllBirds()
    console.log(r)
    console.log('🌱 Seeding done 🏁')
  }

  @Command({
    command: 'seed:reset',
    describe: 'delete all data from the database',
  })
  async delete() {
    console.log('🌱 Start deleting')
    await this.seedService.deleteAllBirds()
    console.log('🌱 Deleting done 🏁')
  }
}

```
### seed.module.ts
- Hier combineer je de seed.command en seed.service
- Je importeert
  -  de TypeOrmModule voor de gewenste entities 
  -  de CommandModule van nestjs-command. Vergeet je deze dan krijg een error
     -  `UnknownModuleException [Error]: Nest could not select the given module (it does not exist in current context)`

```typescript
import { Module } from '@nestjs/common'
import { TypeOrmModule } from '@nestjs/typeorm'
import { Bird } from '../birds/entities/bird.entity'
import { DatabaseSeedService } from './seed.service'
import { DatabaseSeedCommand } from './seed.command'
import { CommandModule } from 'nestjs-command' //https://www.npmjs.com/package/nestjs-command

@Module({
  imports: [TypeOrmModule.forFeature([Bird]), CommandModule], //<---import CommandModule
  providers: [DatabaseSeedCommand, DatabaseSeedService],
})
export class DatabaseSeedModule {}

```

### app.module.ts
- hier importeer je DatabaseSeedModule
  
```typescript
import { DatabaseSeedModule } from './seed/seed.module'

@Module({
  imports: [
    // ....
    DatabaseSeedModule,
  ],

  providers: [],
})
export class AppModule {}

```

### cli.ts
- Als je straks het command `npx nestjs-command seed:database` uitvoert wordt er gezocht naar cli.ts.
- Hier start de NestFactory geen webapplicatie op maar een command applicatie.

**cli.ts**
```typescript
import { NestFactory } from '@nestjs/core';
import { CommandModule, CommandService } from 'nestjs-command';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.createApplicationContext(AppModule, {
    logger: false,
  });
  try {
    await app.select(CommandModule).get(CommandService).exec();
    await app.close();
  } catch (error) {
    console.error(error);
    await app.close();
    process.exit(1);
  }
}

bootstrap();
```
## Gebruik van commando's
Vergeet niet dat je deze uitvoert vanuit de backend folder
```
npx nestjs-command seed:database
npx nestjs-command seed:reset
```

**Comment by christophe-laprudence-howest** [comment]
Hebben we testdata voor birds? @MLoth
